### ISSUE TITLE
Analysis aborted and error appeared when running whole process, using video 20231019-t1_siCep55-50-2

### ISSUE THREAD

**Issue by Tadvedissian** [15bonte/cut-detector#2]
Here is the error message:

KeyError                                  Traceback (most recent call last)
File src\psygnal\_signal.py:990, in _run_emit_loop()

File src\psygnal\_weak_callback.py:321, in cb()

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\magicgui\widgets\_function_gui.py:224, in FunctionGui.__init__.<locals>._disable_button_and_call()
    223 try:
--> 224     self.__call__()
        self = <FunctionGui whole_process(img_layer: napari.layers.image.image.Image = <Image layer 'siCep55-2' at 0x20e8f52d2d0>, img_viewer: napari.viewer.Viewer = Viewer(camera=Camera(center=(0.0, 549.5, 799.5), zoom=0.1045, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(142.0, 1.0, 0.0, 0.0), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=2, last_used=0, range=((0.0, 285.0, 1.0), (0.0, 3.0, 1.0), (0.0, 1100.0, 1.0), (0.0, 1600.0, 1.0)), current_step=(142, 1, 549, 799), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'siCep55-2' at 0x20e8f52d2d0>], help='use <2> for transform', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x0000020EE54DB640>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir: str = WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box: str = True, segmentation_model: str = WindowsPath('.'), fast_mode_check_box: bool = True, save_check_box: bool = True, movies_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2'), results_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2'))>
    225 finally:

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\magicgui\widgets\_function_gui.py:342, in FunctionGui.__call__(self=<FunctionGui whole_process(img_layer: napari.lay...dowsPath('C:/Users/taadvedi/Desktop/siCep55-2'))>, *args=(), **kwargs={})
    341 with _function_name_pointing_to_widget(self):
--> 342     value = self._function(*bound.args, **bound.kwargs)
        self = <FunctionGui whole_process(img_layer: napari.layers.image.image.Image = <Image layer 'siCep55-2' at 0x20e8f52d2d0>, img_viewer: napari.viewer.Viewer = Viewer(camera=Camera(center=(0.0, 549.5, 799.5), zoom=0.1045, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(142.0, 1.0, 0.0, 0.0), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=2, last_used=0, range=((0.0, 285.0, 1.0), (0.0, 3.0, 1.0), (0.0, 1100.0, 1.0), (0.0, 1600.0, 1.0)), current_step=(142, 1, 549, 799), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'siCep55-2' at 0x20e8f52d2d0>], help='use <2> for transform', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x0000020EE54DB640>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir: str = WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box: str = True, segmentation_model: str = WindowsPath('.'), fast_mode_check_box: bool = True, save_check_box: bool = True, movies_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2'), results_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2'))>
        bound = <BoundArguments (img_layer=<Image layer 'siCep55-2' at 0x20e8f52d2d0>, img_viewer=Viewer(camera=Camera(center=(0.0, 549.5, 799.5), zoom=0.1045, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(142.0, 1.0, 0.0, 0.0), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=2, last_used=0, range=((0.0, 285.0, 1.0), (0.0, 3.0, 1.0), (0.0, 1100.0, 1.0), (0.0, 1600.0, 1.0)), current_step=(142, 1, 549, 799), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'siCep55-2' at 0x20e8f52d2d0>], help='use <2> for transform', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x0000020EE54DB640>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir=WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box=True, segmentation_model=WindowsPath('.'), fast_mode_check_box=True, save_check_box=True, movies_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2'), results_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2'))>
        self._function = <function whole_process at 0x0000020E8F47F400>
    344 self._call_count += 1

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\cut_detector\_widget.py:111, in whole_process(img_layer=<Image layer 'siCep55-2'>, img_viewer=Viewer(camera=Camera(center=(0.0, 549.5, 799.5),...ouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir=WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box=True, segmentation_model='.', fast_mode_check_box=True, save_check_box=True, movies_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2'), results_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2'))
    110 # Results saving
--> 111 perform_results_saving(exported_mitoses_dir, save_dir=results_save_dir)
        exported_mitoses_dir = 'C:\\Users\\taadvedi\\AppData\\Local\\Temp\\tmpyxrk8jrf'
        results_save_dir = WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2')
    113 # Delete temporary folders

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\cut_detector\widget_functions\save_results.py:322, in perform_results_saving(exported_mitoses_dir=r'C:\Users\taadvedi\AppData\Local\Temp\tmpyxrk8jrf', show=False, save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2'), verbose=False)
    321 # Save results in as csv file
--> 322 save_csv_results(mitosis_tracks, save_dir)
        mitosis_tracks = [<cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000020E95FACD60>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000020FFC430A30>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000020FFC433D30>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000020E95FAD210>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000020FFC4036D0>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x00000212579BC7C0>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000020E919371F0>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000021257A0A9B0>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x00000212578E4A00>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x00000211D13E27D0>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x000002100FC89F60>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x000002100FC88670>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000020E917F5240>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000020E918C89D0>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000020E918C8790>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000021005146440>, <cut_detector.utils.mitosis_track.MitosisTrack object at 0x0000021005145A20>]
        save_dir = WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2')
    324 # Plot results

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\cut_detector\widget_functions\save_results.py:208, in save_csv_results(mitosis_tracks=[<cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>, <cut_detector.utils.mitosis_track.MitosisTrack object>], save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siCep55-2'))
    207 f.write(f"{daughter_ids};")
--> 208 f.write(f"{mitosis_track.key_events_frame['metaphase']};")
        f = <_io.TextIOWrapper name='C:\\Users\\taadvedi\\Desktop\\siCep55-2\\results.csv' mode='a' encoding='cp1252'>
        mitosis_track = <cut_detector.utils.mitosis_track.MitosisTrack object at 0x00000212579BC7C0>
        mitosis_track.key_events_frame = {'cytokinesis': 14, 'first_mt_cut': <ImpossibleDetection.LIGHT_SPOT: -7>, 'second_mt_cut': <ImpossibleDetection.LIGHT_SPOT: -7>}
    209 cytokinesis_frame = mitosis_track.key_events_frame["cytokinesis"]

KeyError: 'metaphase'

The above exception was the direct cause of the following exception:

EmitLoopError                             Traceback (most recent call last)
File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\magicgui\widgets\bases\_value_widget.py:71, in ValueWidget._on_value_change(self=PushButton(value=False, annotation=None, name='call_button'), value=False)
     69 if value is self.null_value and not self._nullable:
     70     return
---> 71 self.changed.emit(value)
        value = False
        self.changed = <SignalInstance 'changed' on PushButton(value=False, annotation=None, name='call_button')>
        self = PushButton(value=False, annotation=None, name='call_button')

File src\psygnal\_signal.py:945, in emit()

File src\psygnal\_signal.py:992, in _run_emit_loop()

EmitLoopError:
While emitting signal 'magicgui.widgets.PushButton.changed', an error occurred in callback 'magicgui.widgets._function_gui.FunctionGui.__init__.<locals>._disable_button_and_call'.
The args passed to the callback were: (False,)
This is not a bug in psygnal.  See 'KeyError' above for details.

**Comment by 15bonte** [comment]
Will be solved in 0.0.7.
