### ISSUE TITLE
An error appeared when trying to launch two analysis in a row

### ISSUE THREAD

**Issue by Tadvedissian** [15bonte/cut-detector#3]
Here is the error message:

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
File src\psygnal\_signal.py:990, in _run_emit_loop()

File src\psygnal\_weak_callback.py:321, in cb()

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\magicgui\widgets\_function_gui.py:224, in FunctionGui.__init__.<locals>._disable_button_and_call()
    223 try:
--> 224     self.__call__()
        self = <FunctionGui whole_process(img_layer: napari.layers.image.image.Image = <Image layer 'siLuci-2' at 0x1d74919fe80>, img_viewer: napari.viewer.Viewer = Viewer(camera=Camera(center=(0.0, 549.5, 799.5), zoom=0.1045, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(142.0, 1.0, -2010.3086018982399, 684.6674433807582), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=2, last_used=0, range=((0.0, 285.0, 1.0), (0.0, 3.0, 1.0), (0.0, 1100.0, 1.0), (0.0, 1600.0, 1.0)), current_step=(142, 1, 549, 799), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'siLuci-1' at 0x1d45ae0d810>, <Image layer 'siLuci-2' at 0x1d74919fe80>], help='use <2> for transform', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001D432F8B640>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir: str = WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box: str = True, segmentation_model: str = WindowsPath('.'), fast_mode_check_box: bool = True, save_check_box: bool = True, movies_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siLuci-2'), results_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siLuci-2'))>
    225 finally:

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\magicgui\widgets\_function_gui.py:342, in FunctionGui.__call__(self=<FunctionGui whole_process(img_layer: napari.lay...ndowsPath('C:/Users/taadvedi/Desktop/siLuci-2'))>, *args=(), **kwargs={})
    341 with _function_name_pointing_to_widget(self):
--> 342     value = self._function(*bound.args, **bound.kwargs)
        self = <FunctionGui whole_process(img_layer: napari.layers.image.image.Image = <Image layer 'siLuci-2' at 0x1d74919fe80>, img_viewer: napari.viewer.Viewer = Viewer(camera=Camera(center=(0.0, 549.5, 799.5), zoom=0.1045, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(142.0, 1.0, -2010.3086018982399, 684.6674433807582), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=2, last_used=0, range=((0.0, 285.0, 1.0), (0.0, 3.0, 1.0), (0.0, 1100.0, 1.0), (0.0, 1600.0, 1.0)), current_step=(142, 1, 549, 799), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'siLuci-1' at 0x1d45ae0d810>, <Image layer 'siLuci-2' at 0x1d74919fe80>], help='use <2> for transform', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001D432F8B640>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir: str = WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box: str = True, segmentation_model: str = WindowsPath('.'), fast_mode_check_box: bool = True, save_check_box: bool = True, movies_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siLuci-2'), results_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siLuci-2'))>
        bound = <BoundArguments (img_layer=<Image layer 'siLuci-2' at 0x1d74919fe80>, img_viewer=Viewer(camera=Camera(center=(0.0, 549.5, 799.5), zoom=0.1045, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(142.0, 1.0, -2010.3086018982399, 684.6674433807582), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=2, last_used=0, range=((0.0, 285.0, 1.0), (0.0, 3.0, 1.0), (0.0, 1100.0, 1.0), (0.0, 1600.0, 1.0)), current_step=(142, 1, 549, 799), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'siLuci-1' at 0x1d45ae0d810>, <Image layer 'siLuci-2' at 0x1d74919fe80>], help='use <2> for transform', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001D432F8B640>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir=WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box=True, segmentation_model=WindowsPath('.'), fast_mode_check_box=True, save_check_box=True, movies_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siLuci-2'), results_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siLuci-2'))>
        self._function = <function whole_process at 0x000001D45AD6F400>
    344 self._call_count += 1

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\cut_detector\_widget.py:70, in whole_process(img_layer=<Image layer 'siLuci-2'>, img_viewer=Viewer(camera=Camera(center=(0.0, 549.5, 799.5),...ouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir=WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box=True, segmentation_model=WindowsPath('.'), fast_mode_check_box=True, save_check_box=True, movies_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siLuci-2'), results_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siLuci-2'))
     69 video_path = img_viewer.layers[0].source.path
---> 70 assert img_layer.name == os.path.basename(video_path).split(".")[0]
        video_path = 'C:/Users/taadvedi/Desktop/siLuci-1.tif'
        img_layer = <Image layer 'siLuci-2' at 0x1d74919fe80>
        os.path = <module 'ntpath' from 'C:\\ProgramData\\anaconda3\\envs\\cut_detector_7\\lib\\ntpath.py'>
     72 # Create temporary folders

AssertionError:

The above exception was the direct cause of the following exception:

EmitLoopError                             Traceback (most recent call last)
File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\magicgui\widgets\bases\_value_widget.py:71, in ValueWidget._on_value_change(self=PushButton(value=False, annotation=None, name='call_button'), value=False)
     69 if value is self.null_value and not self._nullable:
     70     return
---> 71 self.changed.emit(value)
        value = False
        self.changed = <SignalInstance 'changed' on PushButton(value=False, annotation=None, name='call_button')>
        self = PushButton(value=False, annotation=None, name='call_button')

File src\psygnal\_signal.py:945, in emit()

File src\psygnal\_signal.py:992, in _run_emit_loop()

EmitLoopError:
While emitting signal 'magicgui.widgets.PushButton.changed', an error occurred in callback 'magicgui.widgets._function_gui.FunctionGui.__init__.<locals>._disable_button_and_call'.
The args passed to the callback were: (False,)
This is not a bug in psygnal.  See 'AssertionError' above for details.

**Comment by 15bonte** [comment]
Will be solved in v0.0.7.
