### ISSUE TITLE
New error happening while running whole process

### ISSUE THREAD

**Issue by Tadvedissian** [15bonte/cut-detector#5]
We obtain the following message during the analysis:

Detect MT cut (5/63)...
Detect MT cut (6/63)...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File src\psygnal\_signal.py:990, in _run_emit_loop()

File src\psygnal\_weak_callback.py:321, in cb()

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\magicgui\widgets\_function_gui.py:224, in FunctionGui.__init__.<locals>._disable_button_and_call()
    223 try:
--> 224     self.__call__()
        self = <FunctionGui whole_process(img_layer: napari.layers.image.image.Image = <Image layer 'siSpastin-3' at 0x12fb8b54e80>, img_viewer: napari.viewer.Viewer = Viewer(camera=Camera(center=(0.0, 549.5, 799.5), zoom=0.1045, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(142.0, 1.0, -1570.1172276454581, 1402.3707709668065), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=2, last_used=0, range=((0.0, 285.0, 1.0), (0.0, 3.0, 1.0), (0.0, 1100.0, 1.0), (0.0, 1600.0, 1.0)), current_step=(142, 1, 549, 799), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'siSpastin-4' at 0x12fb25e9720>, <Image layer 'siSpastin-3' at 0x12fb8b54e80>], help='use <2> for transform', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x0000012F88F63B50>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir: str = WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box: str = True, segmentation_model: str = WindowsPath('.'), fast_mode_check_box: bool = True, save_check_box: bool = True, movies_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siSpastin-3'), results_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siSpastin-3'))>
    225 finally:

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\magicgui\widgets\_function_gui.py:342, in FunctionGui.__call__(self=<FunctionGui whole_process(img_layer: napari.lay...wsPath('C:/Users/taadvedi/Desktop/siSpastin-3'))>, *args=(), **kwargs={})
    341 with _function_name_pointing_to_widget(self):
--> 342     value = self._function(*bound.args, **bound.kwargs)
        self = <FunctionGui whole_process(img_layer: napari.layers.image.image.Image = <Image layer 'siSpastin-3' at 0x12fb8b54e80>, img_viewer: napari.viewer.Viewer = Viewer(camera=Camera(center=(0.0, 549.5, 799.5), zoom=0.1045, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(142.0, 1.0, -1570.1172276454581, 1402.3707709668065), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=2, last_used=0, range=((0.0, 285.0, 1.0), (0.0, 3.0, 1.0), (0.0, 1100.0, 1.0), (0.0, 1600.0, 1.0)), current_step=(142, 1, 549, 799), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'siSpastin-4' at 0x12fb25e9720>, <Image layer 'siSpastin-3' at 0x12fb8b54e80>], help='use <2> for transform', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x0000012F88F63B50>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir: str = WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box: str = True, segmentation_model: str = WindowsPath('.'), fast_mode_check_box: bool = True, save_check_box: bool = True, movies_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siSpastin-3'), results_save_dir: str = WindowsPath('C:/Users/taadvedi/Desktop/siSpastin-3'))>
        bound = <BoundArguments (img_layer=<Image layer 'siSpastin-3' at 0x12fb8b54e80>, img_viewer=Viewer(camera=Camera(center=(0.0, 549.5, 799.5), zoom=0.1045, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(142.0, 1.0, -1570.1172276454581, 1402.3707709668065), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=2, last_used=0, range=((0.0, 285.0, 1.0), (0.0, 3.0, 1.0), (0.0, 1100.0, 1.0), (0.0, 1600.0, 1.0)), current_step=(142, 1, 549, 799), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'siSpastin-4' at 0x12fb25e9720>, <Image layer 'siSpastin-3' at 0x12fb8b54e80>], help='use <2> for transform', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x0000012F88F63B50>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir=WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box=True, segmentation_model=WindowsPath('.'), fast_mode_check_box=True, save_check_box=True, movies_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siSpastin-3'), results_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siSpastin-3'))>
        self._function = <function whole_process at 0x0000012FB2543AC0>
    344 self._call_count += 1

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\cut_detector\_widget.py:126, in whole_process(img_layer=<Image layer 'siSpastin-3'>, img_viewer=Viewer(camera=Camera(center=(0.0, 549.5, 799.5),...ouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), fiji_dir=WindowsPath('C:/Users/Public/Downloads/Fiji.app'), default_model_check_box=True, segmentation_model='.', fast_mode_check_box=True, save_check_box=True, movies_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siSpastin-3'), results_save_dir=WindowsPath('C:/Users/taadvedi/Desktop/siSpastin-3'))
    125 # MT cut detection
--> 126 perform_mt_cut_detection(raw_video, img_layer.name, exported_mitoses_dir)
        exported_mitoses_dir = 'C:\\Users\\taadvedi\\AppData\\Local\\Temp\\tmpm_f0_5rx'
        raw_video = <class 'numpy.ndarray'> (285, 1100, 1600, 3) uint16
        img_layer = <Image layer 'siSpastin-3' at 0x12fb8b54e80>
    128 # Results saving

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\cut_detector\widget_functions\mt_cut_detection.py:38, in perform_mt_cut_detection(raw_video=<class 'numpy.ndarray'> (285, 1100, 1600, 3) uint16, video_name='siSpastin-3', exported_mitoses_dir=r'C:\Users\taadvedi\AppData\Local\Temp\tmpm_f0_5rx', scaler_path=r'C:\ProgramData\anaconda3\envs\cut_detector_7\lib...ckages\cut_detector\models\svc_bridges/scaler.pkl', model_path=r'C:\ProgramData\anaconda3\envs\cut_detector_7\lib...ackages\cut_detector\models\svc_bridges/model.pkl', hmm_bridges_parameters_file=r'C:\ProgramData\anaconda3\envs\cut_detector_7\lib...es\cut_detector\models\hmm_bridges_parameters.npz')
     37 # Perform cut detection
---> 38 mt_cut_detector.update_mt_cut_detection(
        mt_cut_detector = <cut_detector.factories.mt_cut_detection_factory.MtCutDetectionFactory object at 0x0000012FBB1859C0>
        mitosis_track = <cut_detector.utils.mitosis_track.MitosisTrack object at 0x00000131CF39AEC0>
        raw_video = <class 'numpy.ndarray'> (285, 1100, 1600, 3) uint16
        scaler_path = 'C:\\ProgramData\\anaconda3\\envs\\cut_detector_7\\lib\\site-packages\\cut_detector\\models\\svc_bridges/scaler.pkl'
        model_path = 'C:\\ProgramData\\anaconda3\\envs\\cut_detector_7\\lib\\site-packages\\cut_detector\\models\\svc_bridges/model.pkl'
        hmm_bridges_parameters_file = 'C:\\ProgramData\\anaconda3\\envs\\cut_detector_7\\lib\\site-packages\\cut_detector\\models\\hmm_bridges_parameters.npz'
     39     mitosis_track, raw_video, scaler_path, model_path, hmm_bridges_parameters_file
     40 )
     42 # Save updated mitosis track

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\cut_detector\factories\mt_cut_detection_factory.py:697, in MtCutDetectionFactory.update_mt_cut_detection(self=<cut_detector.factories.mt_cut_detection_factory.MtCutDetectionFactory object>, mitosis_track=<cut_detector.utils.mitosis_track.MitosisTrack object>, video=<class 'numpy.ndarray'> (285, 1100, 1600, 3) uint16, scaler_path=r'C:\ProgramData\anaconda3\envs\cut_detector_7\lib...ckages\cut_detector\models\svc_bridges/scaler.pkl', model_path=r'C:\ProgramData\anaconda3\envs\cut_detector_7\lib...ackages\cut_detector\models\svc_bridges/model.pkl', hmm_bridges_parameters_file=r'C:\ProgramData\anaconda3\envs\cut_detector_7\lib...es\cut_detector\models\hmm_bridges_parameters.npz')
    696 first_mt_cut_frame_abs = first_frame + first_mt_cut_frame_rel
--> 697 if mitosis_track.light_spot_detected(
        mitosis_track = <cut_detector.utils.mitosis_track.MitosisTrack object at 0x00000131CF39AEC0>
        video = <class 'numpy.ndarray'> (285, 1100, 1600, 3) uint16
        first_mt_cut_frame_abs = 253
        self.length_light_spot = 10
        self = <cut_detector.factories.mt_cut_detection_factory.MtCutDetectionFactory object at 0x0000012FBB1859C0>
        self.crop_size_light_spot = 20
        self.h_maxima_light_spot = 130
        self.intensity_threshold_light_spot = 350
        self.center_tolerance_light_spot = 5
        self.min_percentage_light_spot = 0.1
    698     video,
    699     first_mt_cut_frame_abs,
    700     self.length_light_spot,
    701     self.crop_size_light_spot,
    702     self.h_maxima_light_spot,
    703     self.intensity_threshold_light_spot,
    704     self.center_tolerance_light_spot,
    705     self.min_percentage_light_spot,
    706 ):
    707     mitosis_track.key_events_frame["first_mt_cut"] = ImpossibleDetection.LIGHT_SPOT

File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\cut_detector\utils\mitosis_track.py:613, in MitosisTrack.light_spot_detected(self=<cut_detector.utils.mitosis_track.MitosisTrack object>, video=<class 'numpy.ndarray'> (285, 264, 316, 3) uint16, first_cut_frame=253, length_light_spot=10, crop_size_light_spot=20, h_maxima_light_spot=130, intensity_threshold_light_spot=350, center_tolerance_light_spot=5, min_percentage_light_spot=0.1, print_enabled=False)
    612 # Get mid-body coordinates
--> 613 x_pos, y_pos = self.mid_body_spots[frame].position
        frame = 248
        self.mid_body_spots = {252: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC4AC0>, 253: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC7790>, 254: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC5ED0>, 255: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC6AD0>, 256: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC7490>, 257: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC7E80>, 258: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC4DC0>, 259: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC7910>, 260: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC4A00>, 261: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC5810>, 262: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC4FD0>, 263: <cut_detector.utils.mid_body_spot.MidBodySpot object at 0x00000131DCCC6650>}
        self = <cut_detector.utils.mitosis_track.MitosisTrack object at 0x00000131CF39AEC0>
    615 # Extract image and crop on the midbody

KeyError: 248

The above exception was the direct cause of the following exception:

EmitLoopError                             Traceback (most recent call last)
File C:\ProgramData\anaconda3\envs\cut_detector_7\lib\site-packages\magicgui\widgets\bases\_value_widget.py:71, in ValueWidget._on_value_change(self=PushButton(value=False, annotation=None, name='call_button'), value=False)
     69 if value is self.null_value and not self._nullable:
     70     return
---> 71 self.changed.emit(value)
        value = False
        self.changed = <SignalInstance 'changed' on PushButton(value=False, annotation=None, name='call_button')>
        self = PushButton(value=False, annotation=None, name='call_button')

File src\psygnal\_signal.py:945, in emit()

File src\psygnal\_signal.py:992, in _run_emit_loop()

EmitLoopError:
While emitting signal 'magicgui.widgets.PushButton.changed', an error occurred in callback 'magicgui.widgets._function_gui.FunctionGui.__init__.<locals>._disable_button_and_call'.
The args passed to the callback were: (False,)
This is not a bug in psygnal.  See 'KeyError' above for details.

**Comment by 15bonte** [comment]
Will be solved in v0.0.10
